site_name: Manual de Usuario - NoteERP
site_url: https://carlosescribano17.github.io/proyecto_25_26/
repo_url: https://github.com/carlosescribano17/proyecto_25_26
repo_name: proyecto_25_26

theme:
  name: material
  language: es
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true

nav:
  - Inicio: index.md
  - Introducción: guia/introduccion.md
  - Uso Básico: guia/uso_basico.md
  - Ventas: guia/ventas.md
  - Productos: guia/productos.md
  - Clientes: guia/clientes.md
  - Usuarios: guia/usuarios.md
  - Informes: guia/informes.md
