/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import dao.LineaVentaDAO;
import dao.VentaDAO;
import java.awt.Frame;
import javax.swing.JOptionPane;
import model.LineaVenta;
import model.Venta;

/**
 *
 * @author carlo
 */
public class JDialogPago extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogPago.class.getName());

    /**
     * Creates new form JDialogPago
     */
    
    private panelCarrito carrito;
    private jPanelVentas2 panelVentas;
    
    
    public JDialogPago(Frame parent, boolean modal, panelCarrito carrito, jPanelVentas2 panelVentas) {
        super(parent, modal);
        this.carrito = carrito;
        this.panelVentas = panelVentas;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonTarjeta = new javax.swing.JButton();
        jButtonEfectivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonTarjeta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonTarjeta.setText("TARJETA");
        jButtonTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTarjetaActionPerformed(evt);
            }
        });

        jButtonEfectivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEfectivo.setText("EFECTIVO");
        jButtonEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEfectivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButtonTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jButtonEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTarjetaActionPerformed
        
        panelVentas.hacerCompra("TARJETA");
        
        carrito.vaciarCarrito();
        
        JOptionPane.showMessageDialog(this, 
                "Venta realizada con éxito.",
                "Pago completado", 
                JOptionPane.INFORMATION_MESSAGE);
        
        dispose();
    }//GEN-LAST:event_jButtonTarjetaActionPerformed

    private void jButtonEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEfectivoActionPerformed
        JDialogEfectivo jde = new JDialogEfectivo(
            (Frame) this.getParent(),
            true,
            carrito,
            panelVentas
        );
        jde.setLocationRelativeTo(this);
        jde.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_jButtonEfectivoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEfectivo;
    private javax.swing.JButton jButtonTarjeta;
    // End of variables declaration//GEN-END:variables
}
