/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;


import dao.ClienteDAO;
import javax.swing.JOptionPane;
import model.Cliente;

/**
 *
 * @author DAM2Alu7
 */
public class JDialogAltaCliente extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogAltaCliente.class.getName());

    /**
     * Creates new form JDialogAltaCliente
     */
    MenuPrincipal jframepadre;
    public JDialogAltaCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        jframepadre = (MenuPrincipal) parent;
        initComponents();
        DarkThemeUtil.apply(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombre = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabelC = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombreCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldApellidoCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDNICliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTelefonoCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldEmailCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldDireccionCliente = new javax.swing.JTextField();
        jButtonEnviarC = new javax.swing.JButton();

        jLabelNombre.setText("Nombre");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelC.setText("ALTA CLIENTE");

        jPanel2.setLayout(new java.awt.GridLayout(6, 2, 10, 10));

        jLabel2.setText("Nombre                                           *");
        jPanel2.add(jLabel2);
        jPanel2.add(jTextFieldNombreCliente);

        jLabel3.setText("Apellidos                                         *");
        jPanel2.add(jLabel3);
        jPanel2.add(jTextFieldApellidoCliente);

        jLabel4.setText("DNI                                                   *");
        jPanel2.add(jLabel4);
        jPanel2.add(jTextFieldDNICliente);

        jLabel5.setText("Teléfono                                          *");
        jPanel2.add(jLabel5);
        jPanel2.add(jTextFieldTelefonoCliente);

        jLabel7.setText("Email");
        jPanel2.add(jLabel7);
        jPanel2.add(jTextFieldEmailCliente);

        jLabel8.setText("Dirección");
        jPanel2.add(jLabel8);
        jPanel2.add(jTextFieldDireccionCliente);

        jButtonEnviarC.setText("Enviar");
        jButtonEnviarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEnviarC, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelC, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEnviarC)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnviarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarCActionPerformed
        String nombre = jTextFieldNombreCliente.getText().trim();
        String apellidos = jTextFieldApellidoCliente.getText().trim();
        String dni = jTextFieldDNICliente.getText().trim();
        String telefono = jTextFieldTelefonoCliente.getText().trim();
        String email = jTextFieldEmailCliente.getText().trim();
        
        if(nombre.isEmpty()||apellidos.isEmpty()||dni.isEmpty()||telefono.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nombre, Apellidos, DNI y telefono son obligatorios", "ERROR", JOptionPane.ERROR_MESSAGE);
            jTextFieldNombreCliente.requestFocus();
            return;
        }
        
        if (!dni.matches("\\d{8}[A-Za-z]")) {
            JOptionPane.showMessageDialog(this, "El campo 'DNI' debe tener 8 números seguidos de una letra.", "Error", JOptionPane.ERROR_MESSAGE);
            jTextFieldDNICliente.requestFocus();
            return;
        }
        
        if (telefono.isEmpty() || !telefono.matches("\\d{9}")){
            JOptionPane.showMessageDialog(this, "El campo 'Teléfono' debe tener exactamente 9 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
            jTextFieldTelefonoCliente.requestFocus();
            return;
        }
        
        if (email.isEmpty() || !email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            JOptionPane.showMessageDialog(this, "El campo 'Email' no es válido.", "Error", JOptionPane.ERROR_MESSAGE);
            jTextFieldEmailCliente.requestFocus();
            return;
        }
        
        Cliente nuevo = new Cliente ();
                nuevo.setNombre(nombre);
                nuevo.setApellidos(apellidos);
                nuevo.setDni(dni);
                nuevo.setTelefono(telefono);
                nuevo.setEmail(email);
                nuevo.setDireccion(jTextFieldDireccionCliente.getText());
                //nuevo.setFecha_alta(NOW());
                ClienteDAO cdao = new ClienteDAO();
                
                 if (cdao.insertar(nuevo)) {
                    dispose();
                    JOptionPane.showMessageDialog(this, "Cliente creado correctamente");
                    java.awt.EventQueue.invokeLater(() -> {
                        jframepadre.cargarClientes();
                    });
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Error al crear el cliente.",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
        
    }//GEN-LAST:event_jButtonEnviarCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogAltaCliente dialog = new JDialogAltaCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviarC;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelC;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldApellidoCliente;
    private javax.swing.JTextField jTextFieldDNICliente;
    private javax.swing.JTextField jTextFieldDireccionCliente;
    private javax.swing.JTextField jTextFieldEmailCliente;
    private javax.swing.JTextField jTextFieldNombreCliente;
    private javax.swing.JTextField jTextFieldTelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
