/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;


import dao.ProductoDAO;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Producto;

/**
 *
 * @author DAM2Alu7
 */
public class JDialogAltaProducto extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogAltaProducto.class.getName());

    /**
     * Creates new form JDialogAltaCliente
     */
    MenuPrincipal jframepadre;
    public JDialogAltaProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        jframepadre = (MenuPrincipal) parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombre = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMarca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxTipoProd = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jSpinnerPrecio = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jSpinnerStock = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDescripción = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldImagenURL = new javax.swing.JTextField();
        jButtonEnviar = new javax.swing.JButton();

        jLabelNombre.setText("Nombre");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ALTA PRODUCTO");

        jPanel2.setLayout(new java.awt.GridLayout(8, 2, 10, 10));

        jLabel2.setText("Nombre");
        jPanel2.add(jLabel2);
        jPanel2.add(jTextFieldNombre);

        jLabel3.setText("Marca");
        jPanel2.add(jLabel3);
        jPanel2.add(jTextFieldMarca);

        jLabel4.setText("Tipo de Producto");
        jPanel2.add(jLabel4);

        jComboBoxTipoProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GUITARRA", "AMPLIFICADOR", "ACCESORIO" }));
        jPanel2.add(jComboBoxTipoProd);

        jLabel5.setText("Precio");
        jPanel2.add(jLabel5);

        jSpinnerPrecio.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));
        jPanel2.add(jSpinnerPrecio);

        jLabel6.setText("Stock");
        jPanel2.add(jLabel6);

        jSpinnerStock.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel2.add(jSpinnerStock);

        jLabel7.setText("Descripción");
        jPanel2.add(jLabel7);
        jPanel2.add(jTextFieldDescripción);

        jLabel8.setText("Imagen URL");
        jPanel2.add(jLabel8);
        jPanel2.add(jTextFieldImagenURL);

        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEnviar)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        Producto nuevo = new Producto ();
                nuevo.setNombre(jTextFieldNombre.getText());
                nuevo.setMarca(jTextFieldMarca.getText());
                nuevo.setPrecio((Double) jSpinnerPrecio.getValue());
                nuevo.setStock((int) jSpinnerStock.getValue());
                nuevo.setTipo_producto(jComboBoxTipoProd.getSelectedItem().toString());
                nuevo.setDescripcion(jTextFieldDescripción.getText());
                nuevo.setImagen_url(jTextFieldImagenURL.getText());
                //nuevo.setFecha_alta(NOW());
                ProductoDAO pdao = new ProductoDAO();
                
                 if (pdao.crear(nuevo)) {
                    dispose();
                    jframepadre.cargarProductosPorTipo();
                    JOptionPane.showMessageDialog(this, "Producto creado correctamente");
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Error al crear el producto.",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
        
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogAltaProducto dialog = new JDialogAltaProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JComboBox<String> jComboBoxTipoProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinnerPrecio;
    private javax.swing.JSpinner jSpinnerStock;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldDescripción;
    private javax.swing.JTextField jTextFieldImagenURL;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
