/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class JDialogEfectivo extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogEfectivo.class.getName());

    /**
     * Creates new form JDialogEfectivo
     */
    
    private panelCarrito carrito;
    private jPanelVentas2 panelVentas;
    
    public JDialogEfectivo(Frame parent, boolean modal, panelCarrito carrito, jPanelVentas2 panelVentas) {
        super(parent, modal);
        this.carrito = carrito;
        this.panelVentas = panelVentas;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConfirmar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelImporte = new javax.swing.JLabel();
        jTextFieldEntrega = new javax.swing.JTextField();
        jLabelCambio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("PAGO EFECTIVO");

        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        jLabelImporte.setText("Importe entregado por el cliente");
        jPanel1.add(jLabelImporte);
        jPanel1.add(jTextFieldEntrega);

        jLabelCambio.setText("Cambio: 0,00€");
        jPanel1.add(jLabelCambio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButtonConfirmar)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarPago(java.awt.event.ActionEvent evt) {

        double total = carrito.calcularTotalPedido();
        
        double entregado;
        
        try {
            entregado = Double.parseDouble(jTextFieldEntrega.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Introduce un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (entregado < total) {
            JOptionPane.showMessageDialog(this, "El importe entregado es insuficiente.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double cambio = entregado - total;
        jLabelCambio.setText("Cambio: " + String.format("%.2f", cambio) + " €");

        panelVentas.hacerCompra("EFECTIVO");
            
        JOptionPane.showMessageDialog(this, 
                "Pago en efectivo registrado.\nCambio: " + String.format("%.2f", cambio) + " €",
                "Pago completado", -
                JOptionPane.INFORMATION_MESSAGE);
        carrito.vaciarCarrito();
        dispose();
    }
    
    
    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        confirmarPago(evt);
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCambio;
    private javax.swing.JLabel jLabelImporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldEntrega;
    // End of variables declaration//GEN-END:variables
}
