/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import dao.ProductoDAO;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.UIManager;
import model.Producto;
import model.Usuario;
import java.sql.Timestamp;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DAM2Alu10
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());
    
    private CardLayout cardLayout;
    private Usuario userActual;
    DefaultTableModel dtm;
    ProductoDAO pdao = new ProductoDAO();
    private boolean comboListo = false;
    private java.util.Set<Integer> filasModificadas = new java.util.HashSet<>();

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(Usuario user) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        this.userActual = user;
        
        
        cardLayout = (CardLayout) jPanelVentanaUnica.getLayout();
        cardLayout.show(jPanelVentanaUnica, "card2");
        
        jLabelUsuario.setText("Bienvenid@, "+userActual.getUsuario());
        
        dtm = new DefaultTableModel(pdao.obtenerNombresColumnas(), 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return true;
            }
        };
        jTableProductos.setModel(dtm);
        dtm.addTableModelListener(e -> { //habilita el botón en cuanto haya un cambio en la tabla
            if (e.getType() == javax.swing.event.TableModelEvent.UPDATE) {
                int fila = e.getFirstRow();

                filasModificadas.add(fila);

                if (filasModificadas.size() == 1) {
                    jButtonModificar.setEnabled(true);
                } else {
                    jButtonModificar.setEnabled(false);
                    JOptionPane.showMessageDialog(this,
                            "Solo puedes modificar una fila a la vez.",
                            "Aviso",
                            JOptionPane.WARNING_MESSAGE);
                    cargarProductosPorTipo();        
                    }
            }
        });
        jTableProductos.setAutoCreateRowSorter(false);
        dtm.setColumnIdentifiers(pdao.obtenerNombresColumnas());
        jButtonModificar.setEnabled(false);
        comboListo = true;
    }
    
//    private void inicializarComboBoxTipoProducto() {
//        jComboBoxTipoProducto.addItem("TODOS");
//        jComboBoxTipoProducto.addItem("GUITARRA");
//        jComboBoxTipoProducto.addItem("AMPLIFICADOR");
//        jComboBoxTipoProducto.addItem("ACCESORIO");
//
//        // Listener para cuando cambie la selección
//        jComboBoxTipoProducto.addActionListener(evt -> {
//            cargarProductosPorTipo();
//        });
//    }

    public void cargarProductosPorTipo() {
    // Limpiar la tabla
        dtm.setRowCount(0);

        String tipoSeleccionado = (String) jComboBoxTipoProducto.getSelectedItem();

        java.util.List<Producto> productos;
        if ("TODOS".equals(tipoSeleccionado)) {
            productos = pdao.listarTodos();
        } else {
            productos = pdao.listarPorTipo(tipoSeleccionado);
        }

        // Agregar productos a la tabla
        for (Producto p : productos) {
            Object[] fila = new Object[]{
                p.getId_producto(),
                p.getNombre(),
                p.getMarca(),
                p.getPrecio(),
                p.getStock(),
                p.getTipo_producto(),
                p.getDescripcion(),
                p.getImagen_url(),
                p.getActivo(),
                p.getFecha_alta()
            };
            dtm.addRow(fila);
        }
        filasModificadas.clear();
        jButtonModificar.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVentanaUnica = new javax.swing.JPanel();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnVentas = new javax.swing.JButton();
        btnArticulos = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnStock = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jPanelVentas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVolverVentas = new javax.swing.JButton();
        jPanelClientes = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnVolverClientes = new javax.swing.JButton();
        jPanelArticulos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnVolverArticulos = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jComboBoxTipoProducto = new javax.swing.JComboBox<>();
        jButtonModificar = new javax.swing.JButton();
        jButtonNuevo = new javax.swing.JButton();
        jPanelStock = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnVolverStock = new javax.swing.JButton();
        jPanelUsuarios = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnVolverUsuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TPV NoteERP");

        jPanelVentanaUnica.setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.GridLayout(3, 2, 0, 70));

        btnVentas.setText("VENTAS");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVentas);

        btnArticulos.setText("ARTICULOS");
        btnArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArticulosActionPerformed(evt);
            }
        });
        jPanel1.add(btnArticulos);

        btnClientes.setText("CLIENTES");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnClientes);

        jPanel2.setLayout(new java.awt.GridLayout(3, 2, 0, 70));

        btnStock.setText("STOCK");
        btnStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockActionPerformed(evt);
            }
        });
        jPanel2.add(btnStock);

        btnUsuarios.setText("USUARIOS");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jPanel2.add(btnUsuarios);

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir);

        jLabelUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(238, 238, 238));
        jLabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUsuario.setText("Bienvenid@, ");

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14))))
        );

        jPanelVentanaUnica.add(jPanelPrincipal, "principal");

        jLabel1.setText("Ventas");

        btnVolverVentas.setText("Volver");
        btnVolverVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVentasLayout = new javax.swing.GroupLayout(jPanelVentas);
        jPanelVentas.setLayout(jPanelVentasLayout);
        jPanelVentasLayout.setHorizontalGroup(
            jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentasLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1468, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVentasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolverVentas)
                .addGap(68, 68, 68))
        );
        jPanelVentasLayout.setVerticalGroup(
            jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentasLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 741, Short.MAX_VALUE)
                .addComponent(btnVolverVentas)
                .addGap(47, 47, 47))
        );

        jPanelVentanaUnica.add(jPanelVentas, "ventas");

        jLabel2.setText("Clientes");

        btnVolverClientes.setText("Volver");
        btnVolverClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelClientesLayout = new javax.swing.GroupLayout(jPanelClientes);
        jPanelClientes.setLayout(jPanelClientesLayout);
        jPanelClientesLayout.setHorizontalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientesLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1468, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolverClientes)
                .addGap(68, 68, 68))
        );
        jPanelClientesLayout.setVerticalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientesLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 741, Short.MAX_VALUE)
                .addComponent(btnVolverClientes)
                .addGap(47, 47, 47))
        );

        jPanelVentanaUnica.add(jPanelClientes, "clientes");

        jLabel3.setText("Artículos");

        btnVolverArticulos.setText("Volver");
        btnVolverArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverArticulosActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProductos);

        jComboBoxTipoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "GUITARRA", "AMPLIFICADOR", "ACCESORIO" }));
        jComboBoxTipoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoProductoActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelArticulosLayout = new javax.swing.GroupLayout(jPanelArticulos);
        jPanelArticulos.setLayout(jPanelArticulosLayout);
        jPanelArticulosLayout.setHorizontalGroup(
            jPanelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelArticulosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonNuevo)
                .addGap(55, 55, 55)
                .addComponent(jButtonModificar)
                .addGap(51, 51, 51)
                .addComponent(jButtonBorrar)
                .addGap(76, 76, 76)
                .addComponent(btnVolverArticulos)
                .addGap(68, 68, 68))
            .addGroup(jPanelArticulosLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addGroup(jPanelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelArticulosLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(510, 510, 510)
                        .addComponent(jComboBoxTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanelArticulosLayout.setVerticalGroup(
            jPanelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArticulosLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addGroup(jPanelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolverArticulos)
                    .addComponent(jButtonBorrar)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonNuevo))
                .addGap(47, 47, 47))
        );

        jPanelVentanaUnica.add(jPanelArticulos, "articulos");

        jLabel4.setText("Stock");

        btnVolverStock.setText("Volver");
        btnVolverStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelStockLayout = new javax.swing.GroupLayout(jPanelStock);
        jPanelStock.setLayout(jPanelStockLayout);
        jPanelStockLayout.setHorizontalGroup(
            jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStockLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1468, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStockLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolverStock)
                .addGap(68, 68, 68))
        );
        jPanelStockLayout.setVerticalGroup(
            jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStockLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 741, Short.MAX_VALUE)
                .addComponent(btnVolverStock)
                .addGap(47, 47, 47))
        );

        jPanelVentanaUnica.add(jPanelStock, "stock");

        jLabel5.setText("Usuarios");

        btnVolverUsuarios.setText("Volver");
        btnVolverUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUsuariosLayout = new javax.swing.GroupLayout(jPanelUsuarios);
        jPanelUsuarios.setLayout(jPanelUsuariosLayout);
        jPanelUsuariosLayout.setHorizontalGroup(
            jPanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuariosLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1468, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUsuariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolverUsuarios)
                .addGap(68, 68, 68))
        );
        jPanelUsuariosLayout.setVerticalGroup(
            jPanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuariosLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 741, Short.MAX_VALUE)
                .addComponent(btnVolverUsuarios)
                .addGap(47, 47, 47))
        );

        jPanelVentanaUnica.add(jPanelUsuarios, "usuarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelVentanaUnica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelVentanaUnica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        cardLayout.show(jPanelVentanaUnica,"clientes");
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
        cardLayout.show(jPanelVentanaUnica,"ventas");
    }//GEN-LAST:event_btnVentasActionPerformed

    
    private void btnVolverVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverVentasActionPerformed
        // TODO add your handling code here:
        cardLayout.show(jPanelVentanaUnica,"principal");
    }//GEN-LAST:event_btnVolverVentasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVolverClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverClientesActionPerformed
        // TODO add your handling code here:
        cardLayout.show(jPanelVentanaUnica,"principal");
    }//GEN-LAST:event_btnVolverClientesActionPerformed

    private void btnArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArticulosActionPerformed
        cardLayout.show(jPanelVentanaUnica,"articulos");
        cargarProductosPorTipo();
    }//GEN-LAST:event_btnArticulosActionPerformed

    private void btnVolverArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverArticulosActionPerformed
        // TODO add your handling code here:
        cardLayout.show(jPanelVentanaUnica,"principal");
    }//GEN-LAST:event_btnVolverArticulosActionPerformed

    private void btnVolverStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverStockActionPerformed
        // TODO add your handling code here:
        cardLayout.show(jPanelVentanaUnica,"principal");
    }//GEN-LAST:event_btnVolverStockActionPerformed

    private void btnStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockActionPerformed
        // TODO add your handling code here:
        cardLayout.show(jPanelVentanaUnica,"stock");
    }//GEN-LAST:event_btnStockActionPerformed

    private void btnVolverUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverUsuariosActionPerformed
        // TODO add your handling code here:
        cardLayout.show(jPanelVentanaUnica,"principal");                 
    }//GEN-LAST:event_btnVolverUsuariosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        cardLayout.show(jPanelVentanaUnica,"usuarios");
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        int[] filas = jTableProductos.getSelectedRows();

        if (filas.length == 0) {
            JOptionPane.showMessageDialog(this, "Selecciona al menos un producto.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que deseas borrar los productos seleccionados?",
                "Confirmar borrado",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) return;

        for (int i = filas.length - 1; i >= 0; i--) {

            int fila = filas[i];
            int idProducto = (int) jTableProductos.getValueAt(fila, 0);

            if (pdao.borrar(idProducto)) {
                dtm.removeRow(fila);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Error al borrar el producto con ID: " + idProducto,
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }

        JOptionPane.showMessageDialog(this, "Productos borrados correctamente");
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jComboBoxTipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoProductoActionPerformed
        if(!comboListo) return;
        cargarProductosPorTipo();
    }//GEN-LAST:event_jComboBoxTipoProductoActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        int fila = jTableProductos.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un producto para modificar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Producto p = new Producto();
            p.setId_producto((int) dtm.getValueAt(fila, 0));
            p.setNombre((String) dtm.getValueAt(fila, 1));
            p.setMarca((String) dtm.getValueAt(fila, 2));
            p.setPrecio(Double.parseDouble(dtm.getValueAt(fila, 3).toString()));
            p.setStock(Integer.parseInt(dtm.getValueAt(fila, 4).toString()));
            p.setTipo_producto((String) dtm.getValueAt(fila, 5));
            p.setDescripcion((String) dtm.getValueAt(fila, 6));
            p.setImagen_url((String) dtm.getValueAt(fila, 7));
            p.setActivo(Integer.parseInt(dtm.getValueAt(fila, 8).toString()));

            pdao.actualizar(p);

            JOptionPane.showMessageDialog(this, "Producto modificado correctamente.");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, 
                "Error al modificar el producto: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        filasModificadas.clear();
        jButtonModificar.setEnabled(false);
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        JDialogAltaProducto jdp = new JDialogAltaProducto(this, true);
        jdp.setVisible(true);
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        try {
//            UIManager.setLookAndFeel(new FlatMacDarkLaf());
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArticulos;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnStock;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVentas;
    private javax.swing.JButton btnVolverArticulos;
    private javax.swing.JButton btnVolverClientes;
    private javax.swing.JButton btnVolverStock;
    private javax.swing.JButton btnVolverUsuarios;
    private javax.swing.JButton btnVolverVentas;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JComboBox<String> jComboBoxTipoProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelArticulos;
    private javax.swing.JPanel jPanelClientes;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelStock;
    private javax.swing.JPanel jPanelUsuarios;
    private javax.swing.JPanel jPanelVentanaUnica;
    private javax.swing.JPanel jPanelVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProductos;
    // End of variables declaration//GEN-END:variables
}
