/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.ProductoDAO;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Producto;

/**
 *
 * @author jorge
 */
public class panelProductos extends javax.swing.JPanel {

    /**
     * Creates new form panelProductos
     */
    private ProductoDAO pdao;
    private JTable tablaListado;
    private DefaultTableModel modeloListado;
    private JScrollPane scrollListado;
    private jPanelVentas2 parent;
    
    public panelProductos(jPanelVentas2 parent) {
        this.parent = parent;
        initComponents();
        
        
        // DAO
        pdao = new ProductoDAO();

        // Preparar tabla (no la añadimos aún al initComponents para no tocar código generado)
        tablaListado = new JTable();
        modeloListado = new DefaultTableModel(new String[]{
            "id_producto", "nombre", "marca", "precio", "stock", "tipo_producto",
            "descripcion", "imagen_url", "activo", "fecha_alta"
        }, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // listado solo lectura
            }
        };
        tablaListado.setModel(modeloListado);
        scrollListado = new JScrollPane(tablaListado);

        // Reemplazamos el contenido visual del panelListado por el scroll (limpiamos y usamos BorderLayout)
        panelListado.removeAll();
        panelListado.setLayout(new BorderLayout());
        panelListado.add(scrollListado, BorderLayout.CENTER);
        
        this.add(panelListado, "Listado");
        this.add(panelTipos, "Tipos");
        
        mostrarTipos();
        
        tablaListado.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getClickCount() == 2) { // doble clic
                pasarProductoAlCarrito();
            }
        }
    });

    }

    /**
     * Carga productos por tipo usando ProductoDAO y actualiza la tabla.
     * tipo debe coincidir con los valores que haya en la BD (p.e. "ACCESORIO", "GUITARRA", "AMPLIFICADOR")
     */
    public void cargarListadoPorTipo(String tipo) {
        // Vaciar modelo
        modeloListado.setRowCount(0);

        // Obtener lista desde DAO
        List<Producto> productos = pdao.listarPorTipo(tipo);

        // Rellenar filas (asegúrate que getters coinciden con tu modelo)
        for (Producto p : productos) {
            Object[] fila = new Object[]{
                p.getId_producto(),
                p.getNombre(),
                p.getMarca(),
                p.getPrecio(),
                p.getStock(),
                p.getTipo_producto(),
                p.getDescripcion(),
                p.getImagen_url(),
                p.getActivo(),
                p.getFecha_alta()
            };
            modeloListado.addRow(fila);
        }

        // Mostrar listado
        mostrarListado();
    }
    
    public void mostrarTipos() {
        CardLayout cl = (CardLayout)(this.getLayout());
        cl.show(this, "Tipos");
    }

    public void mostrarListado() {
        CardLayout cl = (CardLayout)(this.getLayout());
        cl.show(this, "Listado");
    }
    
    private void pasarProductoAlCarrito() {
        int fila = tablaListado.getSelectedRow();
        if (fila == -1) return;

        Producto p = new Producto();
        p.setId_producto((int) modeloListado.getValueAt(fila, 0));
        p.setNombre((String) modeloListado.getValueAt(fila, 1));
        p.setMarca((String) modeloListado.getValueAt(fila, 2));
        p.setPrecio((double) modeloListado.getValueAt(fila, 3));
        p.setStock((int) modeloListado.getValueAt(fila, 4));
        p.setTipo_producto((String) modeloListado.getValueAt(fila, 5));
        p.setDescripcion((String) modeloListado.getValueAt(fila, 6));
        p.setImagen_url((String) modeloListado.getValueAt(fila, 7));
        p.setActivo((int) modeloListado.getValueAt(fila, 8));
        p.setFecha_alta((java.sql.Timestamp) modeloListado.getValueAt(fila, 9));

        parent.getCarritoPanel().agregarProducto(p);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelListado = new javax.swing.JPanel();
        pruebaListado = new javax.swing.JLabel();
        panelTipos = new javax.swing.JPanel();
        btnAccesorios = new javax.swing.JButton();
        btnAmplificadores = new javax.swing.JButton();
        btnGuitarras = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        panelListado.setBackground(new java.awt.Color(0, 102, 255));

        pruebaListado.setText("jLabel1");

        javax.swing.GroupLayout panelListadoLayout = new javax.swing.GroupLayout(panelListado);
        panelListado.setLayout(panelListadoLayout);
        panelListadoLayout.setHorizontalGroup(
            panelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListadoLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(pruebaListado, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        panelListadoLayout.setVerticalGroup(
            panelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListadoLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(pruebaListado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(340, Short.MAX_VALUE))
        );

        add(panelListado, "card2");

        panelTipos.setBackground(new java.awt.Color(153, 102, 0));

        btnAccesorios.setText("accesorios");
        btnAccesorios.addActionListener(this::btnAccesoriosActionPerformed);

        btnAmplificadores.setText("amplificadores");
        btnAmplificadores.addActionListener(this::btnAmplificadoresActionPerformed);

        btnGuitarras.setText("guitarras");
        btnGuitarras.addActionListener(this::btnGuitarrasActionPerformed);

        javax.swing.GroupLayout panelTiposLayout = new javax.swing.GroupLayout(panelTipos);
        panelTipos.setLayout(panelTiposLayout);
        panelTiposLayout.setHorizontalGroup(
            panelTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTiposLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(panelTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAccesorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAmplificadores, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addComponent(btnGuitarras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        panelTiposLayout.setVerticalGroup(
            panelTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTiposLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnAmplificadores, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnGuitarras, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnAccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(panelTipos, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccesoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccesoriosActionPerformed
        // TODO add your handling code here:
        pruebaListado.setText("accesorios");
        cargarListadoPorTipo("ACCESORIO");
    }//GEN-LAST:event_btnAccesoriosActionPerformed

    private void btnAmplificadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmplificadoresActionPerformed
        pruebaListado.setText("amplis");
        cargarListadoPorTipo("AMPLIFICADOR");
    }//GEN-LAST:event_btnAmplificadoresActionPerformed

    private void btnGuitarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuitarrasActionPerformed
        pruebaListado.setText("guitarras");
        cargarListadoPorTipo("GUITARRA");
    }//GEN-LAST:event_btnGuitarrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccesorios;
    private javax.swing.JButton btnAmplificadores;
    private javax.swing.JButton btnGuitarras;
    private javax.swing.JPanel panelListado;
    private javax.swing.JPanel panelTipos;
    private javax.swing.JLabel pruebaListado;
    // End of variables declaration//GEN-END:variables
}
