/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.ProductoDAO;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Producto;

/**
 *
 * @author jorge
 */
public class panelProductos extends javax.swing.JPanel {

    /**
     * Creates new form panelProductos
     */
    private ProductoDAO pdao;
    private JTable tablaListado;
    private DefaultTableModel modeloListado;
    private JScrollPane scrollListado;
    private jPanelVentas2 parent;
    
    public panelProductos(jPanelVentas2 parent) {
        this.parent = parent;
        initComponents();
        
        pdao = new ProductoDAO();
        btnAccesorios.setText("ACCESORIOS");
        btnAmplificadores.setText("AMPLIFICADORES");
        btnGuitarras.setText("GUITARRAS");
        tablaListado = new JTable();
        modeloListado = new DefaultTableModel(new String[]{
            "id_producto", "nombre", "marca", "precio", "stock", "tipo_producto",
            "descripcion", "imagen_url", "activo", "fecha_alta"
        }, 0) {
            //para que solo se pueda leer
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaListado.setModel(modeloListado);
        scrollListado = new JScrollPane(tablaListado);

        panelListado.removeAll();
        panelListado.setLayout(new BorderLayout());
        panelListado.add(scrollListado, BorderLayout.CENTER);
        
        this.add(panelListado, "Listado");
        this.add(panelTipos, "Tipos");
        
        mostrarTipos();
        
        tablaListado.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            Producto seleccionado = obtenerProductoSeleccionado();
            parent.mostrarProductoSeleccionado(seleccionado);
            //meter producto al carrito si se hace doble click
            if (evt.getClickCount() == 2) {
                pasarProductoAlCarrito();
            }
        }
    });
        DarkThemeUtil.apply(this);

    }

    public void cargarListadoPorTipo(String tipo) {
        modeloListado.setRowCount(0);

        List<Producto> productos = pdao.listarPorTipo(tipo);

        for (Producto p : productos) {
            Object[] fila = new Object[]{
                p.getId_producto(),
                p.getNombre(),
                p.getMarca(),
                p.getPrecio(),
                p.getStock(),
                p.getTipo_producto(),
                p.getDescripcion(),
                p.getImagen_url(),
                p.getActivo(),
                p.getFecha_alta()
            };
            modeloListado.addRow(fila);
        }

        mostrarListado();
    }
    
    public void mostrarTipos() {
        CardLayout cl = (CardLayout)(this.getLayout());
        cl.show(this, "Tipos");
    }

    public void mostrarListado() {
        CardLayout cl = (CardLayout)(this.getLayout());
        cl.show(this, "Listado");
    }
    
    private void pasarProductoAlCarrito() {
        Producto p = obtenerProductoSeleccionado();
        if (p == null) return;
        parent.getCarritoPanel().agregarProducto(p);
    }
    
    private Producto obtenerProductoSeleccionado() {
        int filaVista = tablaListado.getSelectedRow();
        if (filaVista == -1) return null;
        int fila = tablaListado.convertRowIndexToModel(filaVista);

        Producto p = new Producto();

        p.setId_producto((int) modeloListado.getValueAt(fila, 0));
        p.setNombre((String) modeloListado.getValueAt(fila, 1));
        p.setMarca((String) modeloListado.getValueAt(fila, 2));
        p.setPrecio((double) modeloListado.getValueAt(fila, 3));
        p.setStock((int) modeloListado.getValueAt(fila, 4));
        p.setTipo_producto((String) modeloListado.getValueAt(fila, 5));
        p.setDescripcion((String) modeloListado.getValueAt(fila, 6));
        p.setImagen_url((String) modeloListado.getValueAt(fila, 7));
        p.setActivo((int) modeloListado.getValueAt(fila, 8));
        p.setFecha_alta((java.sql.Timestamp) modeloListado.getValueAt(fila, 9));

        return p;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelListado = new javax.swing.JPanel();
        pruebaListado = new javax.swing.JLabel();
        panelTipos = new javax.swing.JPanel();
        btnAmplificadores = new javax.swing.JButton();
        btnAccesorios = new javax.swing.JButton();
        btnGuitarras = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        panelListado.setBackground(new java.awt.Color(0, 102, 255));
        panelListado.setPreferredSize(null);

        pruebaListado.setText("jLabel1");

        javax.swing.GroupLayout panelListadoLayout = new javax.swing.GroupLayout(panelListado);
        panelListado.setLayout(panelListadoLayout);
        panelListadoLayout.setHorizontalGroup(
            panelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListadoLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(pruebaListado, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        panelListadoLayout.setVerticalGroup(
            panelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListadoLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(pruebaListado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(340, Short.MAX_VALUE))
        );

        add(panelListado, "card2");

        panelTipos.setBackground(new java.awt.Color(51, 102, 255));
        panelTipos.setLayout(new java.awt.GridBagLayout());

        btnAmplificadores.setText("amplificadores");
        btnAmplificadores.addActionListener(this::btnAmplificadoresActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 2);
        panelTipos.add(btnAmplificadores, gridBagConstraints);

        btnAccesorios.setText("accesorios");
        btnAccesorios.addActionListener(this::btnAccesoriosActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.weighty = 0.1;
        panelTipos.add(btnAccesorios, gridBagConstraints);

        btnGuitarras.setText("guitarras");
        btnGuitarras.addActionListener(this::btnGuitarrasActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.weighty = 0.1;
        panelTipos.add(btnGuitarras, gridBagConstraints);

        add(panelTipos, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccesoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccesoriosActionPerformed
        pruebaListado.setText("ACCESORIOS");
        cargarListadoPorTipo("ACCESORIO");
    }//GEN-LAST:event_btnAccesoriosActionPerformed

    private void btnAmplificadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmplificadoresActionPerformed
        pruebaListado.setText("AMPLIS");
        cargarListadoPorTipo("AMPLIFICADOR");
    }//GEN-LAST:event_btnAmplificadoresActionPerformed

    private void btnGuitarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuitarrasActionPerformed
        pruebaListado.setText("GUITARRAS");
        cargarListadoPorTipo("GUITARRA");
    }//GEN-LAST:event_btnGuitarrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccesorios;
    private javax.swing.JButton btnAmplificadores;
    private javax.swing.JButton btnGuitarras;
    private javax.swing.JPanel panelListado;
    private javax.swing.JPanel panelTipos;
    private javax.swing.JLabel pruebaListado;
    // End of variables declaration//GEN-END:variables
}
