/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.CardLayout;

/**
 *
 * @author jorge
 */
public class panelProductos extends javax.swing.JPanel {

    /**
     * Creates new form panelProductos
     */
    public panelProductos() {
        initComponents();
        
        this.add(panelListado, "Listado");
        this.add(panelTipos, "Tipos");
        
        mostrarTipos();
    }

    public void mostrarTipos() {
        CardLayout cl = (CardLayout)(this.getLayout());
        cl.show(this, "Tipos");
    }

    public void mostrarListado() {
        CardLayout cl = (CardLayout)(this.getLayout());
        cl.show(this, "Listado");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelListado = new javax.swing.JPanel();
        pruebaListado = new javax.swing.JLabel();
        panelTipos = new javax.swing.JPanel();
        btnAccesorios = new javax.swing.JButton();
        btnAmplificadores = new javax.swing.JButton();
        btnGuitarras = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        panelListado.setBackground(new java.awt.Color(0, 102, 255));

        pruebaListado.setText("jLabel1");

        javax.swing.GroupLayout panelListadoLayout = new javax.swing.GroupLayout(panelListado);
        panelListado.setLayout(panelListadoLayout);
        panelListadoLayout.setHorizontalGroup(
            panelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListadoLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(pruebaListado, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        panelListadoLayout.setVerticalGroup(
            panelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListadoLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(pruebaListado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(340, Short.MAX_VALUE))
        );

        add(panelListado, "card2");

        panelTipos.setBackground(new java.awt.Color(153, 102, 0));

        btnAccesorios.setText("accesorios");
        btnAccesorios.addActionListener(this::btnAccesoriosActionPerformed);

        btnAmplificadores.setText("amplificadores");

        btnGuitarras.setText("guitarras");

        javax.swing.GroupLayout panelTiposLayout = new javax.swing.GroupLayout(panelTipos);
        panelTipos.setLayout(panelTiposLayout);
        panelTiposLayout.setHorizontalGroup(
            panelTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTiposLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(panelTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAccesorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAmplificadores, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addComponent(btnGuitarras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        panelTiposLayout.setVerticalGroup(
            panelTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTiposLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnAmplificadores, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnGuitarras, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnAccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(panelTipos, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccesoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccesoriosActionPerformed
        // TODO add your handling code here:
        pruebaListado.setText("accesorios");
        mostrarListado();
        
    }//GEN-LAST:event_btnAccesoriosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccesorios;
    private javax.swing.JButton btnAmplificadores;
    private javax.swing.JButton btnGuitarras;
    private javax.swing.JPanel panelListado;
    private javax.swing.JPanel panelTipos;
    private javax.swing.JLabel pruebaListado;
    // End of variables declaration//GEN-END:variables
}
