/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package E13_ComboList;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author DAM2Alu7
 */
public class JFrameAmigos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameAmigos.class.getName());

    /**
     * Creates new form JFrameAmigos
     */
    DefaultListModel dlm;
    
    private void carga(){
        for (int i = 0; i < 10; i++) {
            dlm.addElement("Persona -> " + i);
            
        }
    }
    public JFrameAmigos() {
        initComponents();
        dlm = new DefaultListModel();
        jListAmigos.setModel(dlm);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelIzq = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jComboBoxCiudad = new javax.swing.JComboBox<>();
        jButtonAnyadir = new javax.swing.JButton();
        jPanelDcha = new javax.swing.JPanel();
        jButtonIndices = new javax.swing.JButton();
        jButtonAmigos = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jPanelCentro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAmigos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("APLICACIÓN AMIGOS");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanelIzq.setLayout(new java.awt.GridLayout(4, 1, 10, 10));

        jLabel2.setText("Nombre");
        jPanelIzq.add(jLabel2);

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jPanelIzq.add(jTextFieldNombre);

        jComboBoxCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Huesca", "Zaragoza", "Teruel" }));
        jPanelIzq.add(jComboBoxCiudad);

        jButtonAnyadir.setText("Añadir");
        jButtonAnyadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnyadirActionPerformed(evt);
            }
        });
        jPanelIzq.add(jButtonAnyadir);

        jPanel1.add(jPanelIzq, java.awt.BorderLayout.LINE_START);

        jPanelDcha.setLayout(new java.awt.GridLayout(3, 1, 10, 10));

        jButtonIndices.setText("Indices Seleccíon");
        jButtonIndices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIndicesActionPerformed(evt);
            }
        });
        jPanelDcha.add(jButtonIndices);

        jButtonAmigos.setText("Indices Amigos");
        jButtonAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAmigosActionPerformed(evt);
            }
        });
        jPanelDcha.add(jButtonAmigos);

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });
        jPanelDcha.add(jButtonBorrar);

        jPanel1.add(jPanelDcha, java.awt.BorderLayout.LINE_END);

        jPanelCentro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Amigos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jListAmigos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListAmigos);

        javax.swing.GroupLayout jPanelCentroLayout = new javax.swing.GroupLayout(jPanelCentro);
        jPanelCentro.setLayout(jPanelCentroLayout);
        jPanelCentroLayout.setHorizontalGroup(
            jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCentroLayout.setVerticalGroup(
            jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelCentro, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnyadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnyadirActionPerformed
        
        String persona = jTextFieldNombre.getText() + " -> " + jComboBoxCiudad.getSelectedItem();
        dlm.addElement(persona);
    }//GEN-LAST:event_jButtonAnyadirActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jButtonIndicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIndicesActionPerformed
        
        if(!jListAmigos.isSelectionEmpty()){
            for (int indice : jListAmigos.getSelectedIndices()) {
                System.out.println("Amigo indice -> " + indice);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "No has seleccionado ningún amigo");
        }
    }//GEN-LAST:event_jButtonIndicesActionPerformed

    private void jButtonAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAmigosActionPerformed
       if(!jListAmigos.isSelectionEmpty()) {
           for (String indice : jListAmigos.getSelectedValuesList()) {
               System.out.println("Lista de amiguetes: " + indice);
           }
       }else{
            JOptionPane.showMessageDialog(rootPane, "No has seleccionado ningún amigo");
        }
    }//GEN-LAST:event_jButtonAmigosActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        if(!jListAmigos.isSelectionEmpty()){
            for (String indice : jListAmigos.getSelectedValuesList()){
                dlm.removeElement(indice);
                System.out.println("Amigos eliminados: " + indice);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "No has seleccionado ningún amigo");
        }
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameAmigos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAmigos;
    private javax.swing.JButton jButtonAnyadir;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonIndices;
    private javax.swing.JComboBox<String> jComboBoxCiudad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListAmigos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCentro;
    private javax.swing.JPanel jPanelDcha;
    private javax.swing.JPanel jPanelIzq;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
