/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package E07_RadioButton;

import java.awt.Color;

/**
 *
 * @author DAM2Alu7
 */
public class JFrameRadio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameRadio.class.getName());

    /**
     * Creates new form JFrameRadio
     */
    public JFrameRadio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelVariableCon = new javax.swing.JLabel();
        jPanelRadio = new javax.swing.JPanel();
        jRadioButtonVerde = new javax.swing.JRadioButton();
        jRadioButtonAzul = new javax.swing.JRadioButton();
        jRadioButtonRojo = new javax.swing.JRadioButton();
        jButtonSelect = new javax.swing.JButton();
        jLabelVariableWithout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelVariableCon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelVariableCon.setForeground(new java.awt.Color(51, 51, 255));
        jLabelVariableCon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVariableCon.setText("COLORES");

        jPanelRadio.setBackground(new java.awt.Color(51, 255, 255));
        jPanelRadio.setForeground(new java.awt.Color(255, 255, 255));
        jPanelRadio.setLayout(new javax.swing.BoxLayout(jPanelRadio, javax.swing.BoxLayout.Y_AXIS));

        buttonGroup1.add(jRadioButtonVerde);
        jRadioButtonVerde.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButtonVerde.setText("Verde");
        jPanelRadio.add(jRadioButtonVerde);

        buttonGroup1.add(jRadioButtonAzul);
        jRadioButtonAzul.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButtonAzul.setText("Azul");
        jPanelRadio.add(jRadioButtonAzul);

        buttonGroup1.add(jRadioButtonRojo);
        jRadioButtonRojo.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButtonRojo.setText("Rojo");
        jPanelRadio.add(jRadioButtonRojo);

        jButtonSelect.setText("Seleccionar");
        jButtonSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectActionPerformed(evt);
            }
        });

        jLabelVariableWithout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelVariableWithout.setForeground(new java.awt.Color(51, 51, 255));
        jLabelVariableWithout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVariableWithout.setText("SIN COLOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRadio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVariableCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jButtonSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
            .addComponent(jLabelVariableWithout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVariableCon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonSelect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabelVariableWithout, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectActionPerformed
        if (jRadioButtonAzul.isSelected()){
            jPanelRadio.setBackground(Color.blue);
        }else if (jRadioButtonRojo.isSelected()){
            jPanelRadio.setBackground(Color.red);
        }else if (jRadioButtonVerde.isSelected()){
            jPanelRadio.setBackground(Color.green);
        }
    }//GEN-LAST:event_jButtonSelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameRadio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonSelect;
    private javax.swing.JLabel jLabelVariableCon;
    private javax.swing.JLabel jLabelVariableWithout;
    private javax.swing.JPanel jPanelRadio;
    private javax.swing.JRadioButton jRadioButtonAzul;
    private javax.swing.JRadioButton jRadioButtonRojo;
    private javax.swing.JRadioButton jRadioButtonVerde;
    // End of variables declaration//GEN-END:variables
}
